#![cfg(feature = "derive")]

use simple_endian::Endianize;

#[test]
fn endianize_generates_wire_and_aliases() {
    #[derive(Endianize)]
    #[endian(be)]
    #[repr(C)]
    #[allow(dead_code)]
    struct Header {
        a: u32,
        b: u16,
    }

    // Generated by the macro.
    let _wire = HeaderWire {
        a: 1u32.into(),
        b: 2u16.into(),
    };
}
